import "../styles/globals.css";
import Header from "./Header";
import Head from "next/head";
import { useRouter } from "next/router";

function MyApp({ Component, pageProps }) {
  const router = useRouter();

  const handleRouter = () => {
    return {
      goToHome: () => router.push("/"),
      goToAbout: () => router.push("/About"),
      goToContact: () => router.push("/Contact"),
    };
  };

  const { goToHome, goToAbout, goToContact } = handleRouter();
  return (
    <>
      <Head>
        <title> Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
      </Head>
      <Header
        goToAbout={goToAbout}
        goToHome={goToHome}
        goToContact={goToContact}
      />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
